// Vanilla tree labels, rank caps, positions and dependencies. Combat adaptations live in classic-talents.ts.
// Factual reference: https://github.com/hseager/Classic-WoW-Talent-Planner/blob/e47aece378dbb27e900898feb73bc9c8a4104b77/assets/data/talent-data.json
import type { ClassId } from "./content";
export type TalentFact = [
  name: string,
  max: number,
  row: number,
  column: number,
  dependency?: number,
  dependencyRank?: number,
];
export const CLASSIC_TALENT_FACTS: Record<ClassId, [string, TalentFact[]][]> = {
  warrior: [
    [
      "Arms",
      [
        ["Improved Heroic Strike", 3, 1, 1],
        ["Deflection", 5, 1, 2],
        ["Improved Rend", 3, 1, 3],
        ["Improved Charge", 2, 2, 1],
        ["Tactical Mastery", 5, 2, 2],
        ["Improved Thunder Clap", 3, 2, 4],
        ["Improved Overpower", 2, 3, 1],
        ["Anger Management", 1, 3, 2, 4, 5],
        ["Deep Wounds", 3, 3, 3, 2, 3],
        ["Two-Handed Weapon Specialization", 5, 4, 2],
        ["Impale", 2, 4, 3, 8, 3],
        ["Axe Specialization", 5, 5, 1],
        ["Sweeping Strikes", 1, 5, 2],
        ["Mace Specialization", 5, 5, 3],
        ["Sword Specialization", 5, 5, 4],
        ["Polearm Specialization", 5, 6, 1],
        ["Improved Hamstring", 3, 6, 3],
        ["Mortal Strike", 1, 7, 2, 12, 1],
      ],
    ],
    [
      "Fury",
      [
        ["Booming Voice", 5, 1, 2],
        ["Cruelty", 5, 1, 3],
        ["Improved Demoralizing Shout", 5, 2, 2],
        ["Unbridled Wrath", 5, 2, 3],
        ["Improved Cleave", 3, 3, 1],
        ["Piercing Howl", 1, 3, 2],
        ["Blood Craze", 3, 3, 3],
        ["Improved Battle Shout", 5, 3, 4],
        ["Dual Wield Specialization", 5, 4, 1],
        ["Improved Execute", 2, 4, 2],
        ["Enrage", 5, 4, 3],
        ["Improved Slam", 5, 5, 1],
        ["Death Wish", 1, 5, 2],
        ["Improved Intercept", 2, 5, 4],
        ["Improved Berserker Rage", 2, 6, 1],
        ["Flurry", 5, 6, 3, 10, 5],
        ["Bloodthirst", 1, 7, 2, 12, 1],
      ],
    ],
    [
      "Protection",
      [
        ["Shield Specialization", 5, 1, 2],
        ["Anticipation", 5, 1, 3],
        ["Improved Bloodrage", 2, 2, 1],
        ["Toughness", 5, 2, 3],
        ["Iron Will", 5, 2, 4],
        ["Last Stand", 1, 3, 1, 2, 2],
        ["Improved Shield Block", 3, 3, 2, 0, 5],
        ["Improved Revenge", 3, 3, 3],
        ["Defiance", 5, 3, 4],
        ["Improved Sunder Armor", 3, 4, 1],
        ["Improved Disarm", 3, 4, 2],
        ["Improved Taunt", 2, 4, 3],
        ["Improved Shield Wall", 2, 5, 1],
        ["Concussion Blow", 1, 5, 2],
        ["Improved Shield Bash", 2, 5, 3],
        ["One-Handed Weapon Specialization", 5, 6, 3],
        ["Shield Slam", 1, 7, 2, 13, 1],
      ],
    ],
  ],
  paladin: [
    [
      "Holy",
      [
        ["Divine Strength", 5, 1, 2],
        ["Divine Intellect", 5, 1, 3],
        ["Spiritual Focus", 5, 2, 2],
        ["Improved Seal of Righteousness", 5, 2, 3],
        ["Healing Light", 3, 3, 1],
        ["Consecration", 1, 3, 2],
        ["Improved Lay on Hands", 2, 3, 3],
        ["Unyielding Faith", 2, 3, 4],
        ["Illumination", 5, 4, 2],
        ["Improved Blessing of Wisdom", 2, 4, 3],
        ["Divine Favor", 1, 5, 2, 8, 5],
        ["Lasting Judgement", 3, 5, 3],
        ["Holy Power", 5, 6, 3],
        ["Holy Shock", 1, 7, 2, 10, 1],
      ],
    ],
    [
      "Protection",
      [
        ["Improved Devotion Aura", 5, 1, 2],
        ["Redoubt", 5, 1, 3],
        ["Precision", 3, 2, 1],
        ["Guardian's Favor", 2, 2, 2],
        ["Toughness", 5, 2, 4],
        ["Blessing of Kings", 1, 3, 1],
        ["Improved Righteous Fury", 3, 3, 2],
        ["Shield Specialization", 3, 3, 3, 1, 5],
        ["Anticipation", 5, 3, 4],
        ["Improved Hammer of Justice", 3, 4, 2],
        ["Improved Concentration Aura", 3, 4, 3],
        ["Blessing of Sanctuary", 1, 5, 2],
        ["Reckoning", 5, 5, 3],
        ["One-Handed Weapon Specialization", 5, 6, 3],
        ["Holy Shield", 1, 7, 2, 11, 1],
      ],
    ],
    [
      "Retribution",
      [
        ["Improved Blessing of Might", 5, 1, 2],
        ["Benediction", 5, 1, 3],
        ["Improved Judgement", 2, 2, 1],
        ["Improved Seal of the Crusader", 3, 2, 2],
        ["Deflection", 5, 2, 3],
        ["Vindication", 3, 3, 1],
        ["Conviction", 5, 3, 2],
        ["Seal of Command", 1, 3, 3],
        ["Pursuit of Justice", 2, 3, 4],
        ["Eye for an Eye", 2, 4, 1],
        ["Improved Retribution Aura", 2, 4, 3],
        ["Two-Handed Weapon Specialization", 3, 5, 1],
        ["Sanctity Aura", 1, 5, 3],
        ["Vengeance", 5, 6, 2, 6, 5],
        ["Repentance", 1, 7, 2],
      ],
    ],
  ],
  hunter: [
    [
      "Beast Mastery",
      [
        ["Improved Aspect of the Hawk", 5, 1, 2],
        ["Endurance Training", 5, 1, 3],
        ["Improved Eyes of the Beast", 2, 2, 1],
        ["Improved Aspect of the Monkey", 5, 2, 2],
        ["Thick Hide", 3, 2, 3],
        ["Improved Revive Pet", 2, 2, 4],
        ["Pathfinding", 2, 3, 1],
        ["Bestial Swiftness", 1, 3, 2],
        ["Unleashed Fury", 5, 3, 3],
        ["Improved Mend Pet", 2, 4, 2],
        ["Ferocity", 5, 4, 3],
        ["Spirit Bond", 2, 5, 1],
        ["Intimidation", 1, 5, 2],
        ["Bestial Discipline", 2, 5, 4],
        ["Frenzy", 5, 6, 3, 10, 5],
        ["Bestial Wrath", 1, 7, 2, 12, 1],
      ],
    ],
    [
      "Marksmanship",
      [
        ["Improved Concussive Shot", 5, 1, 2],
        ["Efficiency", 5, 1, 3],
        ["Improved Hunter's Mark", 5, 2, 2],
        ["Lethal Shots", 5, 2, 3],
        ["Aimed Shot", 1, 3, 1],
        ["Improved Arcane Shot", 5, 3, 2],
        ["Hawk Eye", 3, 3, 4],
        ["Improved Serpent Sting", 5, 4, 2],
        ["Mortal Shots", 5, 4, 3, 3, 5],
        ["Scatter Shot", 1, 5, 1],
        ["Barrage", 3, 5, 2],
        ["Improved Scorpid Sting", 3, 5, 3],
        ["Ranged Weapon Specialization", 5, 6, 3],
        ["Trueshot Aura", 1, 7, 2, 10, 3],
      ],
    ],
    [
      "Survival",
      [
        ["Monster Slaying", 3, 1, 1],
        ["Humanoid Slaying", 3, 1, 2],
        ["Deflection", 5, 1, 3],
        ["Entrapment", 5, 2, 1],
        ["Savage Strikes", 2, 2, 2],
        ["Improved Wing Clip", 5, 2, 3],
        ["Clever Traps", 2, 3, 1],
        ["Survivalist", 5, 3, 2],
        ["Deterrence", 1, 3, 3],
        ["Trap Mastery", 2, 4, 1],
        ["Surefooted", 3, 4, 2],
        ["Improved Feign Death", 2, 4, 4],
        ["Killer Instinct", 3, 5, 2],
        ["Counterattack", 1, 5, 3, 8, 1],
        ["Lightning Reflexes", 5, 6, 3],
        ["Wyvern Sting", 1, 7, 2, 12, 3],
      ],
    ],
  ],
  rogue: [
    [
      "Assassination",
      [
        ["Improved Eviscerate", 3, 1, 1],
        ["Remorseless Attacks", 2, 1, 2],
        ["Malice", 5, 1, 3],
        ["Ruthlessness", 3, 2, 1],
        ["Murder", 2, 2, 2],
        ["Improved Slice and Dice", 3, 2, 4],
        ["Relentless Strikes", 1, 3, 1],
        ["Improved Expose Armor", 2, 3, 2],
        ["Lethality", 5, 3, 3, 2, 5],
        ["Vile Poisons", 5, 4, 2],
        ["Improved Poisons", 5, 4, 3],
        ["Cold Blood", 1, 5, 2],
        ["Improved Kidney Shot", 3, 5, 3],
        ["Seal Fate", 5, 6, 2, 11, 1],
        ["Vigor", 1, 7, 2],
      ],
    ],
    [
      "Combat",
      [
        ["Improved Gouge", 3, 1, 1],
        ["Improved Sinister Strike", 2, 1, 2],
        ["Lightning Reflexes", 5, 1, 3],
        ["Improved Backstab", 3, 2, 1],
        ["Deflection", 5, 2, 2],
        ["Precision", 5, 2, 3],
        ["Endurance", 2, 3, 1],
        ["Riposte", 1, 3, 2, 4, 5],
        ["Improved Sprint", 2, 3, 4],
        ["Improved Kick", 2, 4, 1],
        ["Dagger Specialization", 5, 4, 2],
        ["Dual Wield Specialization", 5, 4, 3, 5, 5],
        ["Mace Specialization", 5, 5, 1],
        ["Blade Flurry", 1, 5, 2],
        ["Sword Specialization", 5, 5, 3],
        ["Fist Weapon Specialization", 5, 5, 4],
        ["Weapon Expertise", 2, 6, 2, 13, 1],
        ["Aggression", 3, 6, 3],
        ["Adrenaline Rush", 1, 7, 2],
      ],
    ],
    [
      "Subtlety",
      [
        ["Master of Deception", 5, 1, 2],
        ["Opportunity", 5, 1, 3],
        ["Sleight of Hand", 2, 2, 1],
        ["Elusiveness", 2, 2, 2],
        ["Camouflage", 5, 2, 3],
        ["Initiative", 3, 3, 1],
        ["Ghostly Strike", 1, 3, 2],
        ["Improved Ambush", 3, 3, 3],
        ["Setup", 3, 4, 1],
        ["Improved Sap", 3, 4, 2],
        ["Serrated Blades", 3, 4, 3],
        ["Heightened Senses", 2, 5, 1],
        ["Preparation", 1, 5, 2],
        ["Dirty Deeds", 2, 5, 3],
        ["Hemorrhage", 1, 5, 4, 10, 3],
        ["Deadliness", 5, 6, 3],
        ["Premeditation", 1, 7, 2, 12, 1],
      ],
    ],
  ],
  priest: [
    [
      "Discipline",
      [
        ["Unbreakable Will", 5, 1, 2],
        ["Wand Specialization", 5, 1, 3],
        ["Silent Resolve", 5, 2, 1],
        ["Improved Power Word: Fortitude", 2, 2, 2],
        ["Improved Power Word: Shield", 3, 2, 3],
        ["Martyrdom", 2, 2, 4],
        ["Inner Focus", 1, 3, 2],
        ["Meditation", 3, 3, 3],
        ["Improved Inner Fire", 3, 4, 1],
        ["Mental Agility", 5, 4, 2],
        ["Improved Mana Burn", 2, 4, 4],
        ["Mental Strength", 5, 5, 2],
        ["Divine Spirit", 1, 5, 3, 7, 3],
        ["Force of Will", 5, 6, 3],
        ["Power Infusion", 1, 7, 2, 11, 5],
      ],
    ],
    [
      "Holy",
      [
        ["Healing Focus", 2, 1, 1],
        ["Improved Renew", 3, 1, 2],
        ["Holy Specialization", 5, 1, 3],
        ["Spell Warding", 5, 2, 2],
        ["Divine Fury", 5, 2, 3],
        ["Holy Nova", 1, 3, 1],
        ["Blessed Recovery", 3, 3, 2],
        ["Inspiration", 3, 3, 4],
        ["Holy Reach", 2, 4, 1],
        ["Improved Healing", 3, 4, 2],
        ["Searing Light", 2, 4, 3, 4, 5],
        ["Improved Prayer of Healing", 3, 5, 1],
        ["Spirit of Redemption", 1, 5, 2],
        ["Spiritual Guidance", 5, 5, 3],
        ["Spiritual Healing", 5, 6, 3],
        ["Lightwell", 1, 7, 2, 12, 1],
      ],
    ],
    [
      "Shadow",
      [
        ["Spirit Tap", 5, 1, 2],
        ["Blackout", 5, 1, 3],
        ["Shadow Affinity", 3, 2, 1],
        ["Improved Shadow Word: Pain", 2, 2, 2],
        ["Shadow Focus", 5, 2, 3],
        ["Improved Psychic Scream", 2, 3, 1],
        ["Improved Mind Blast", 5, 3, 2],
        ["Mind Flay", 1, 3, 3],
        ["Improved Fade", 2, 4, 2],
        ["Shadow Reach", 3, 4, 3],
        ["Shadow Weaving", 5, 4, 4],
        ["Silence", 1, 5, 1, 5, 2],
        ["Vampiric Embrace", 1, 5, 2],
        ["Improved Vampiric Embrace", 2, 5, 3, 12, 1],
        ["Darkness", 5, 6, 3],
        ["Shadowform", 1, 7, 2, 12, 1],
      ],
    ],
  ],
  shaman: [
    [
      "Elemental",
      [
        ["Convection", 5, 1, 2],
        ["Concussion", 5, 1, 3],
        ["Earth's Grasp", 2, 2, 1],
        ["Elemental Warding", 3, 2, 2],
        ["Call of Flame", 3, 2, 3],
        ["Elemental Focus", 1, 3, 1],
        ["Reverberation", 5, 3, 2],
        ["Call of Thunder", 5, 3, 3],
        ["Improved Fire Totems", 2, 4, 1],
        ["Eye of the Storm", 3, 4, 2],
        ["Elemental Devastation", 3, 4, 4],
        ["Storm Reach", 2, 5, 1],
        ["Elemental Fury", 1, 5, 2],
        ["Lightning Mastery", 5, 6, 3, 7, 5],
        ["Elemental Mastery", 1, 7, 2, 12, 1],
      ],
    ],
    [
      "Enhancement",
      [
        ["Ancestral Knowledge", 5, 1, 2],
        ["Shield Specialization", 5, 1, 3],
        ["Guardian Totems", 2, 2, 1],
        ["Thundering Strikes", 5, 2, 2],
        ["Improved Ghost Wolf", 2, 2, 3],
        ["Improved Lightning Shield", 3, 2, 4],
        ["Enhancing Totems", 2, 3, 1],
        ["Two-Handed Axes and Maces", 1, 3, 3],
        ["Anticipation", 5, 3, 4],
        ["Flurry", 5, 4, 2, 3, 5],
        ["Toughness", 5, 4, 3],
        ["Improved Weapon Totems", 2, 5, 1],
        ["Elemental Weapons", 3, 5, 2],
        ["Parry", 1, 5, 3],
        ["Weapon Mastery", 5, 6, 3],
        ["Stormstrike", 1, 7, 2, 12, 3],
      ],
    ],
    [
      "Restoration",
      [
        ["Improved Healing Wave", 5, 1, 2],
        ["Tidal Focus", 5, 1, 3],
        ["Improved Reincarnation", 2, 2, 1],
        ["Ancestral Healing", 3, 2, 2],
        ["Totemic Focus", 5, 2, 3],
        ["Nature's Guidance", 3, 3, 1],
        ["Healing Focus", 5, 3, 2],
        ["Totemic Mastery", 1, 3, 3],
        ["Healing Grace", 3, 3, 4],
        ["Restorative Totems", 5, 4, 2],
        ["Tidal Mastery", 5, 4, 3],
        ["Healing Way", 3, 5, 1],
        ["Nature's Swiftness", 1, 5, 3],
        ["Purification", 5, 6, 3],
        ["Mana Tide Totem", 1, 7, 2, 9, 5],
      ],
    ],
  ],
  mage: [
    [
      "Arcane",
      [
        ["Arcane Subtlety", 2, 1, 1],
        ["Arcane Focus", 5, 1, 2],
        ["Improved Arcane Missiles", 5, 1, 3],
        ["Wand Specialization", 2, 2, 1],
        ["Magic Absorption", 5, 2, 2],
        ["Arcane Concentration", 5, 2, 3],
        ["Magic Attunement", 2, 3, 1],
        ["Improved Arcane Explosion", 3, 3, 2],
        ["Arcane Resilience", 1, 3, 3],
        ["Improved Mana Shield", 2, 4, 1],
        ["Improved Counterspell", 2, 4, 2],
        ["Arcane Meditation", 3, 4, 4],
        ["Presence of Mind", 1, 5, 2],
        ["Arcane Mind", 5, 5, 3, 8, 1],
        ["Arcane Instability", 3, 6, 2, 12, 1],
        ["Arcane Power", 1, 7, 2, 14, 3],
      ],
    ],
    [
      "Fire",
      [
        ["Improved Fireball", 5, 1, 2],
        ["Impact", 5, 1, 3],
        ["Ignite", 5, 2, 1],
        ["Flame Throwing", 2, 2, 2],
        ["Improved Fire Blast", 3, 2, 3],
        ["Incinerate", 2, 3, 1],
        ["Improved Flamestrike", 3, 3, 2],
        ["Pyroblast", 1, 3, 3],
        ["Burning Soul", 2, 3, 4],
        ["Improved Scorch", 3, 4, 1],
        ["Improved Fire Ward", 2, 4, 2],
        ["Master of Elements", 3, 4, 4],
        ["Critical Mass", 3, 5, 2],
        ["Blast Wave", 1, 5, 3, 7, 1],
        ["Fire Power", 5, 6, 3],
        ["Combustion", 1, 7, 2, 12, 3],
      ],
    ],
    [
      "Frost",
      [
        ["Frost Warding", 2, 1, 1],
        ["Improved Frostbolt", 5, 1, 2],
        ["Elemental Precision", 3, 1, 3],
        ["Ice Shards", 5, 2, 1],
        ["Frostbite", 3, 2, 2],
        ["Improved Frost Nova", 2, 2, 3],
        ["Permafrost", 3, 2, 4],
        ["Piercing Ice", 3, 3, 1],
        ["Cold Snap", 1, 3, 2],
        ["Improved Blizzard", 3, 3, 4],
        ["Arctic Reach", 2, 4, 1],
        ["Frost Channeling", 3, 4, 2],
        ["Shatter", 5, 4, 3, 5, 2],
        ["Ice Block", 1, 5, 2],
        ["Improved Cone of Cold", 3, 5, 3],
        ["Winter's Chill", 5, 6, 3],
        ["Ice Barrier", 1, 7, 2, 13, 1],
      ],
    ],
  ],
  warlock: [
    [
      "Affliction",
      [
        ["Suppression", 5, 1, 2],
        ["Improved Corruption", 5, 1, 3],
        ["Improved Curse of Weakness", 3, 2, 1],
        ["Improved Drain Soul", 2, 2, 2],
        ["Improved Life Tap", 2, 2, 3],
        ["Improved Drain Life", 5, 2, 4],
        ["Improved Curse of Agony", 3, 3, 1],
        ["Fel Concentration", 5, 3, 2],
        ["Amplify Curse", 1, 3, 3],
        ["Grim Reach", 2, 4, 1],
        ["Nightfall", 2, 4, 2],
        ["Improved Drain Mana", 2, 4, 4],
        ["Siphon Life", 1, 5, 2],
        ["Curse of Exhaustion", 1, 5, 3, 8, 1],
        ["Improved Curse of Exhaustion", 4, 5, 4, 13, 1],
        ["Shadow Mastery", 5, 6, 2, 12, 1],
        ["Dark Pact", 1, 7, 2],
      ],
    ],
    [
      "Demonology",
      [
        ["Improved Healthstone", 2, 1, 1],
        ["Improved Imp", 3, 1, 2],
        ["Demonic Embrace", 5, 1, 3],
        ["Improved Health Funnel", 2, 2, 1],
        ["Improved Voidwalker", 3, 2, 2],
        ["Fel Intellect", 5, 2, 3],
        ["Improved Succubus", 3, 3, 1],
        ["Fel Domination", 1, 3, 2],
        ["Fel Stamina", 5, 3, 3],
        ["Master Summoner", 2, 4, 2, 7, 1],
        ["Unholy Power", 5, 4, 3],
        ["Improved Enslave Demon", 5, 5, 1],
        ["Demonic Sacrifice", 1, 5, 2],
        ["Improved Firestone", 2, 5, 4],
        ["Master Demonologist", 5, 6, 3, 10, 5],
        ["Soul Link", 1, 7, 2, 12, 1],
        ["Improved Spellstone", 1, 7, 3],
      ],
    ],
    [
      "Destruction",
      [
        ["Improved Shadow Bolt", 5, 1, 2],
        ["Cataclysm", 5, 1, 3],
        ["Bane", 5, 2, 2],
        ["Aftermath", 5, 2, 3],
        ["Improved Firebolt", 2, 3, 1],
        ["Improved Lash of Pain", 2, 3, 2],
        ["Devastation", 5, 3, 3],
        ["Shadowburn", 1, 3, 4],
        ["Intensity", 2, 4, 1],
        ["Destructive Reach", 2, 4, 2],
        ["Improved Searing Pain", 5, 4, 4],
        ["Pyroclasm", 2, 5, 1, 8, 2],
        ["Improved Immolate", 5, 5, 2],
        ["Ruin", 1, 5, 3, 6, 5],
        ["Emberstorm", 5, 6, 3],
        ["Conflagrate", 1, 7, 2, 12, 5],
      ],
    ],
  ],
  druid: [
    [
      "Balance",
      [
        ["Improved Wrath", 5, 1, 1],
        ["Nature's Grasp", 1, 1, 2],
        ["Improved Nature's Grasp", 4, 1, 3, 1, 1],
        ["Improved Entangling Roots", 3, 2, 1],
        ["Improved Moonfire", 5, 2, 2],
        ["Natural Weapons", 5, 2, 3],
        ["Natural Shapeshifter", 3, 2, 4],
        ["Improved Thorns", 3, 3, 1],
        ["Omen of Clarity", 1, 3, 3, 5, 5],
        ["Nature's Reach", 2, 3, 4],
        ["Vengeance", 5, 4, 2, 4, 5],
        ["Improved Starfire", 5, 4, 3],
        ["Nature's Grace", 1, 5, 2],
        ["Moonglow", 3, 5, 3],
        ["Moonfury", 5, 6, 2, 12, 1],
        ["Moonkin Form", 1, 7, 2],
      ],
    ],
    [
      "Feral Combat",
      [
        ["Ferocity", 5, 1, 2],
        ["Feral Aggression", 5, 1, 3],
        ["Feral Instinct", 5, 2, 1],
        ["Brutal Impact", 2, 2, 2],
        ["Thick Hide", 5, 2, 3],
        ["Feline Swiftness", 2, 3, 1],
        ["Feral Charge", 1, 3, 2],
        ["Sharpened Claws", 3, 3, 3],
        ["Improved Shred", 2, 4, 1],
        ["Predatory Strikes", 3, 4, 2],
        ["Blood Frenzy", 2, 4, 3, 7, 3],
        ["Primal Fury", 2, 4, 4, 7, 3],
        ["Savage Fury", 2, 5, 1],
        ["Faerie Fire (Feral)", 1, 5, 3],
        ["Heart of the Wild", 5, 6, 2, 9, 3],
        ["Leader of the Pack", 1, 7, 2],
      ],
    ],
    [
      "Restoration",
      [
        ["Improved Mark of the Wild", 5, 1, 2],
        ["Furor", 5, 1, 3],
        ["Improved Healing Touch", 5, 2, 1],
        ["Nature's Focus", 5, 2, 2],
        ["Improved Enrage", 2, 2, 3],
        ["Reflection", 3, 3, 2],
        ["Insect Swarm", 1, 3, 3],
        ["Subtlety", 5, 3, 4],
        ["Tranquil Spirit", 5, 4, 2],
        ["Improved Rejuvenation", 3, 4, 4],
        ["Nature's Swiftness", 1, 5, 1, 2, 5],
        ["Gift of Nature", 5, 5, 3, 6, 1],
        ["Improved Tranquility", 2, 5, 4],
        ["Improved Regrowth", 5, 6, 3],
        ["Swiftmend", 1, 7, 2, 8, 5],
      ],
    ],
  ],
};
