import type { GearDef } from "./content";

// Original rewards. No dropZones: these items come only from their guardian pools.
export const RAGEFIRE_GEAR: GearDef[] = [
  {
    id: "chasm_stone",
    name: "Chieftain's Hearthstone",
    slot: "trinket",
    icon: "shield",
    rarity: "rare",
    level: 10,
    value: 100,
    stats: { armor: 4, health: 18, magnet: 10 },
    description:
      "A warm stone from the trogg refuge, carved with a warding mark.",
  },
  {
    id: "trogg_grips",
    name: "Stonebreaker Grips",
    slot: "hands",
    icon: "fist",
    armor: "mail",
    rarity: "rare",
    level: 10,
    value: 100,
    stats: { armor: 5, power: 6, health: 15 },
    description: "Heavy linked gloves recovered from the chieftain's hoard.",
  },
  {
    id: "cinder_boots",
    name: "Cinderstep Slippers",
    slot: "boots",
    icon: "boot",
    armor: "cloth",
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { speed: 12, armor: 2, health: 12 },
    description: "Light soles that carry their wearer across cooled basalt.",
  },
  {
    id: "slag_blade",
    name: "Slagforged Edge",
    slot: "weapon",
    icon: "sword",
    classes: ["warrior", "rogue", "paladin"],
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { power: 17, crit: 3 },
    description: "A dark blade quenched above the molten crossing.",
  },
  {
    id: "ash_bow",
    name: "Ashwood Recurve",
    slot: "weapon",
    icon: "bow",
    classes: ["hunter"],
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { power: 17, haste: 5 },
    description: "Fire-blackened wood still holds a sure draw.",
  },
  {
    id: "ember_branch",
    name: "Emberbound Branch",
    slot: "weapon",
    icon: "staff",
    classes: ["mage", "priest", "warlock", "shaman", "druid"],
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { power: 15, haste: 5, health: 20 },
    description: "A crooked focus that retains the crossing's heat.",
  },
  {
    id: "searing_hood",
    name: "Searing Veil",
    slot: "head",
    icon: "helm",
    armor: "cloth",
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { power: 10, regen: 0.8, health: 15 },
    description: "A ritual hood freed from the invoker's binding.",
  },
  {
    id: "invoker_seal",
    name: "Seal of the Quiet Void",
    slot: "trinket",
    icon: "rune",
    rarity: "rare",
    level: 10,
    value: 110,
    stats: { power: 8, haste: 5, regen: 0.3 },
    description: "The sigil grows silent after its master's defeat.",
  },
  {
    id: "satyr_wraps",
    name: "Overlook Nightwraps",
    slot: "chest",
    icon: "robe",
    armor: "leather",
    rarity: "rare",
    level: 10,
    value: 120,
    stats: { power: 11, crit: 5, health: 24 },
    description: "Supple leather worn by the overlook's hidden assassin.",
  },
  {
    id: "cleft_mantle",
    name: "Mantle of the Cleft",
    slot: "chest",
    icon: "robe",
    armor: "cloth",
    rarity: "rare",
    level: 10,
    value: 120,
    stats: { power: 12, health: 28, haste: 5 },
    description: "Fine cloth recovered from the Searing Blade's final cache.",
  },
  {
    id: "chasm_helm",
    name: "Basalt Watchguard",
    slot: "head",
    icon: "helm",
    armor: "mail",
    rarity: "rare",
    level: 10,
    value: 120,
    stats: { armor: 6, power: 10, health: 30 },
    description: "A dark visor that catches the last light above the lava.",
  },
];
