import type { ClassId, SpellDef, SpellBonus } from "./content";

export interface SpellbookProgress {
  learned: string[];
  prepared: string[];
}
export interface ClassTechnique {
  classId: ClassId;
  level: number;
  gold: number;
  school: string;
  parent: string;
  spell: SpellDef;
}
export const CLASS_MENTORS: Record<ClassId, string> = {
  warrior: "Veteran Ironwatch",
  mage: "Arcanist Wintermere",
  rogue: "Shadowblade Duskwick",
  hunter: "Ranger Ashtrail",
  paladin: "Knight Dawnwarden",
  priest: "Chaplain Lightwell",
  shaman: "Spiritwalker Stormreed",
  warlock: "Binder Emberveil",
  druid: "Keeper Moonbough",
};
function technique(
  classId: ClassId,
  level: number,
  school: string,
  parent: string,
  id: string,
  name: string,
  icon: string,
  kind: SpellDef["kind"],
  color: string,
  damage: number,
  cooldown: number,
  range: number,
  cost: number,
  description: string,
  evolution: string,
  extra: Partial<SpellDef> = {},
): ClassTechnique {
  return {
    classId,
    level,
    gold: level === 5 ? 40 : level === 12 ? 120 : level * 12,
    school,
    parent,
    spell: {
      id,
      name,
      icon,
      kind,
      color,
      damage,
      cooldown,
      range,
      cost,
      count: 1,
      description,
      evolution,
      ...extra,
    },
  };
}
export const CLASS_TECHNIQUES: ClassTechnique[] = [
  technique(
    "warrior",
    5,
    "Arms",
    "cleave",
    "rend",
    "Rend",
    "drop",
    "dot",
    "#d09278",
    12,
    3.8,
    115,
    8,
    "Bleed one nearby enemy for three ticks over six seconds. Spreads to unmarked targets.",
    "Bloodletter's Rend",
    { periodic: { ticks: 3, interval: 2 } },
  ),
  technique(
    "warrior",
    12,
    "Arms",
    "execute",
    "heroicstrike",
    "Heroic Strike",
    "sword",
    "melee",
    "#e3c99b",
    55,
    1.9,
    110,
    12,
    "A powerful strike against one nearby enemy.",
    "Champion's Strike",
    { singleTarget: true },
  ),
  technique(
    "mage",
    5,
    "Frost",
    "blizzard",
    "frostnova",
    "Frost Nova",
    "snow",
    "nova",
    "#a3dbea",
    20,
    5.5,
    150,
    16,
    "Root nearby ordinary enemies for 1.2 seconds. Bosses are slowed instead.",
    "Winter's Nova",
    { slow: 0.6, freeze: 1.2 },
  ),
  technique(
    "mage",
    12,
    "Fire",
    "fireball",
    "flamestrike",
    "Flamestrike",
    "flame",
    "ground",
    "#efaa72",
    28,
    6,
    135,
    22,
    "An impact of fire followed by a burning patch beneath an enemy.",
    "Inferno Pillar",
    { impact: 0.7 },
  ),
  technique(
    "rogue",
    5,
    "Assassination",
    "poison",
    "rupture",
    "Rupture",
    "drop",
    "dot",
    "#d38591",
    14,
    3.8,
    105,
    16,
    "Bleed one nearby enemy for four ticks over eight seconds.",
    "Scarlet Rupture",
    { periodic: { ticks: 4, interval: 2 } },
  ),
  technique(
    "rogue",
    12,
    "Combat",
    "sinister",
    "eviscerate",
    "Eviscerate",
    "dagger",
    "melee",
    "#e5b2aa",
    68,
    2.5,
    95,
    24,
    "An energy-heavy finishing strike against one nearby enemy.",
    "Perfect Evisceration",
    { singleTarget: true },
  ),
  technique(
    "hunter",
    5,
    "Survival",
    "shot",
    "serpentsting",
    "Serpent Sting",
    "drop",
    "dot",
    "#a6bf73",
    10,
    3.8,
    600,
    12,
    "Poison an enemy for four ticks over eight seconds. Spreads to unmarked targets.",
    "Venomous Sting",
    { periodic: { ticks: 4, interval: 2 } },
  ),
  technique(
    "hunter",
    12,
    "Marksmanship",
    "multishot",
    "volley",
    "Volley",
    "bow",
    "ground",
    "#d8c09c",
    24,
    5.5,
    145,
    20,
    "Rain arrows into a target area while you keep moving.",
    "Arrow Tempest",
  ),
  technique(
    "paladin",
    5,
    "Holy",
    "judgment",
    "holylight",
    "Holy Light",
    "heart",
    "heal",
    "#f1d696",
    14,
    7,
    0,
    18,
    "Automatically heal yourself while injured. Can critically heal.",
    "Dawn's Light",
  ),
  technique(
    "paladin",
    12,
    "Retribution",
    "hammer",
    "hammerwrath",
    "Hammer of Wrath",
    "sun",
    "projectile",
    "#efcc87",
    80,
    3.8,
    600,
    16,
    "Throw a holy hammer only at an enemy with 20% health or less.",
    "Hammer of Reckoning",
    { executeBelow: 0.2 },
  ),
  technique(
    "priest",
    5,
    "Holy",
    "holynova",
    "renew",
    "Renew",
    "heart",
    "heal",
    "#dfd7a2",
    4.5,
    8,
    0,
    16,
    "Heal yourself in four pulses over eight seconds. Waits while already active or uninjured.",
    "Enduring Renew",
    { periodic: { ticks: 4, interval: 2 } },
  ),
  technique(
    "priest",
    12,
    "Holy",
    "smite",
    "holyfire",
    "Holy Fire",
    "flame",
    "dot",
    "#edbc85",
    9,
    4.5,
    600,
    16,
    "Strike with holy fire, then burn the target for four ticks over eight seconds.",
    "Dawnfire",
    { periodic: { ticks: 4, interval: 2 }, impact: 2 },
  ),
  technique(
    "shaman",
    5,
    "Elemental",
    "lightning",
    "flameshock",
    "Flame Shock",
    "flame",
    "dot",
    "#ed9b71",
    9,
    4,
    550,
    12,
    "An instant fire impact followed by four burning ticks over six seconds.",
    "Searing Shock",
    { periodic: { ticks: 4, interval: 1.5 }, impact: 1.5 },
  ),
  technique(
    "shaman",
    12,
    "Elemental",
    "chainlightning",
    "frostshock",
    "Frost Shock",
    "snow",
    "projectile",
    "#a3d3df",
    40,
    2.8,
    550,
    14,
    "A frost bolt damages an enemy and slows its movement.",
    "Glacial Shock",
    { slow: 0.5 },
  ),
  technique(
    "warlock",
    5,
    "Affliction",
    "corruption",
    "agony",
    "Curse of Agony",
    "skull",
    "dot",
    "#b39abc",
    9,
    4,
    600,
    14,
    "Curse an enemy for six ticks over twelve seconds. Later ticks grow up to 50% stronger.",
    "Agony Unbound",
    { periodic: { ticks: 6, interval: 2, ramp: true } },
  ),
  technique(
    "warlock",
    12,
    "Destruction",
    "immolate",
    "searingpain",
    "Searing Pain",
    "flame",
    "projectile",
    "#e79a76",
    38,
    1.6,
    600,
    12,
    "A quick, focused fire attack against an enemy.",
    "Tormenting Flame",
  ),
  technique(
    "druid",
    5,
    "Restoration",
    "hurricane",
    "rejuvenation",
    "Rejuvenation",
    "leaf",
    "heal",
    "#a9c995",
    5,
    7,
    0,
    14,
    "Heal yourself in three pulses over six seconds without stacking.",
    "Verdant Rejuvenation",
    { periodic: { ticks: 3, interval: 2 } },
  ),
  technique(
    "druid",
    12,
    "Balance",
    "moonfire",
    "starfire",
    "Starfire",
    "moon",
    "projectile",
    "#bdc7e8",
    65,
    2.8,
    650,
    18,
    "A heavy arcane star bolt rewards careful positioning.",
    "Astral Starfire",
  ),
];
// Original survivor implementations of Vanilla specialization techniques.
CLASS_TECHNIQUES.push(
  technique(
    "warrior",
    20,
    "Arms",
    "cleave",
    "mortalstrike",
    "Mortal Strike",
    "sword",
    "melee",
    "#d28d79",
    85,
    3.5,
    135,
    20,
    "A decisive strike against one nearby foe.",
    "Champion's Mortal Strike",
    { singleTarget: true },
  ),
  technique(
    "warrior",
    30,
    "Fury",
    "whirlwind",
    "bloodthirst",
    "Bloodthirst",
    "drop",
    "melee",
    "#c75858",
    52,
    4,
    130,
    18,
    "Strike nearby foes while recovering through your class talents.",
    "Relentless Bloodthirst",
  ),
  technique(
    "warrior",
    40,
    "Protection",
    "thunderclap",
    "shieldslam",
    "Shield Slam",
    "shield",
    "melee",
    "#b9b39a",
    72,
    5,
    140,
    20,
    "A crushing blow that freezes ordinary foes for one second.",
    "Bulwark Slam",
    { freeze: 1 },
  ),
  technique(
    "mage",
    20,
    "Arcane",
    "arcane",
    "arcanepower",
    "Arcane Power",
    "spark",
    "buff",
    "#bba3e0",
    0,
    22,
    0,
    22,
    "Gain 25% damage for eight seconds. Automatic preparation waits for nearby foes.",
    "Archmage's Power",
    { buff: { duration: 8, stats: { power: 25 } } },
  ),
  technique(
    "mage",
    30,
    "Fire",
    "fireball",
    "combustion",
    "Combustion",
    "fire",
    "buff",
    "#eaae72",
    0,
    24,
    0,
    20,
    "Gain 18% critical chance for eight seconds.",
    "Unquenchable Combustion",
    { buff: { duration: 8, stats: { crit: 18 } } },
  ),
  technique(
    "mage",
    40,
    "Frost",
    "blizzard",
    "icebarrier",
    "Ice Barrier",
    "shield",
    "buff",
    "#88cadb",
    0,
    24,
    0,
    22,
    "Absorb 45 damage for eight seconds. Casts when enemies approach.",
    "Glacial Barrier",
    { buff: { duration: 8, shield: 45 } },
  ),
  technique(
    "rogue",
    20,
    "Assassination",
    "poison",
    "coldblood",
    "Cold Blood",
    "drop",
    "buff",
    "#bc819c",
    0,
    22,
    0,
    20,
    "Gain 25% critical chance for six seconds.",
    "Icy Precision",
    { buff: { duration: 6, stats: { crit: 25 } } },
  ),
  technique(
    "rogue",
    30,
    "Combat",
    "flurry",
    "adrenalinerush",
    "Adrenaline Rush",
    "whirl",
    "buff",
    "#d1b07a",
    0,
    25,
    0,
    5,
    "Restore 35 energy and gain 20% cast speed for eight seconds.",
    "Relentless Rush",
    { buff: { duration: 8, resource: 35, stats: { haste: 20 } } },
  ),
  technique(
    "rogue",
    40,
    "Subtlety",
    "sinister",
    "premeditation",
    "Premeditation",
    "target",
    "buff",
    "#9e96cc",
    0,
    20,
    0,
    10,
    "Gain 12% damage and 15% movement speed for eight seconds.",
    "Master's Preparation",
    { buff: { duration: 8, stats: { power: 12, speed: 15 } } },
  ),
  technique(
    "hunter",
    20,
    "Beast Mastery",
    "beast",
    "bestialwrath",
    "Bestial Wrath",
    "wolf",
    "buff",
    "#cb9274",
    0,
    25,
    0,
    20,
    "Gain 22% damage for eight seconds, including your companion.",
    "Primal Wrath",
    { buff: { duration: 8, stats: { power: 22 } } },
  ),
  technique(
    "hunter",
    30,
    "Marksmanship",
    "shot",
    "aimedshot",
    "Aimed Shot",
    "target",
    "projectile",
    "#b9ca86",
    100,
    5.5,
    750,
    22,
    "Launch a heavy piercing arrow at the nearest foe.",
    "Ranger's Aimed Shot",
  ),
  technique(
    "hunter",
    40,
    "Survival",
    "trap",
    "wyvernsting",
    "Wyvern Sting",
    "leaf",
    "dot",
    "#a8b9b2",
    22,
    5,
    650,
    18,
    "Poison one unmarked foe for four ticks over eight seconds.",
    "Ancient Wyvern Sting",
    { periodic: { ticks: 4, interval: 2 } },
  ),
  technique(
    "paladin",
    20,
    "Holy",
    "judgment",
    "holyshock",
    "Holy Shock",
    "sun",
    "nova",
    "#eddb99",
    50,
    5,
    155,
    22,
    "A flash of holy power damages nearby enemies.",
    "Radiant Shock",
  ),
  technique(
    "paladin",
    30,
    "Protection",
    "consecration",
    "holyshield",
    "Holy Shield",
    "shield",
    "buff",
    "#b9c5d4",
    0,
    22,
    0,
    22,
    "Gain 12 armor and absorb 25 damage for eight seconds.",
    "Dawnwarden's Shield",
    { buff: { duration: 8, stats: { armor: 12 }, shield: 25 } },
  ),
  technique(
    "paladin",
    40,
    "Retribution",
    "holystrike",
    "repentance",
    "Repentance",
    "sun",
    "nova",
    "#ddcd8b",
    38,
    7,
    190,
    22,
    "A holy wave holds ordinary enemies still for two seconds.",
    "Judgment of Repentance",
    { freeze: 2 },
  ),
  technique(
    "priest",
    20,
    "Discipline",
    "smite",
    "powerinfusion",
    "Power Infusion",
    "spark",
    "buff",
    "#d6c5ed",
    0,
    24,
    0,
    20,
    "Gain 18% damage and 12% cast speed for eight seconds.",
    "Divine Infusion",
    { buff: { duration: 8, stats: { power: 18, haste: 12 } } },
  ),
  technique(
    "priest",
    30,
    "Holy",
    "holynova",
    "lightwell",
    "Lightwell",
    "sun",
    "heal",
    "#e3d6a1",
    12,
    11,
    0,
    22,
    "Recover in five pulses over ten seconds.",
    "Sanctuary Lightwell",
    { periodic: { ticks: 5, interval: 2 } },
  ),
  technique(
    "priest",
    40,
    "Shadow",
    "pain",
    "shadowform",
    "Shadowform",
    "moon",
    "buff",
    "#a993cf",
    0,
    22,
    0,
    22,
    "Gain 18% damage and eight armor for eight seconds.",
    "Deep Shadowform",
    { buff: { duration: 8, stats: { power: 18, armor: 8 } } },
  ),
  technique(
    "shaman",
    20,
    "Elemental",
    "lightning",
    "elementalmastery",
    "Elemental Mastery",
    "lightning",
    "buff",
    "#9eb8d4",
    0,
    24,
    0,
    20,
    "Gain 20% critical chance and 10% damage for eight seconds.",
    "Storm Master's Focus",
    { buff: { duration: 8, stats: { crit: 20, power: 10 } } },
  ),
  technique(
    "shaman",
    30,
    "Enhancement",
    "totem",
    "stormstrike",
    "Stormstrike",
    "lightning",
    "melee",
    "#b8d1d6",
    72,
    4,
    145,
    20,
    "A lightning-charged strike against nearby enemies.",
    "Thunderlord's Strike",
  ),
  technique(
    "shaman",
    40,
    "Restoration",
    "totem",
    "manatide",
    "Mana Tide Totem",
    "water",
    "buff",
    "#8dbcc9",
    0,
    24,
    0,
    10,
    "Restore 35 mana and gain one regeneration for eight seconds.",
    "Deepwater Tide",
    { buff: { duration: 8, resource: 35, stats: { regen: 1 } } },
  ),
  technique(
    "warlock",
    20,
    "Affliction",
    "corruption",
    "siphonlife",
    "Siphon Life",
    "drop",
    "heal",
    "#b3a4b8",
    9,
    10,
    0,
    18,
    "Recover in four shadow pulses over eight seconds.",
    "Endless Siphon",
    { periodic: { ticks: 4, interval: 2 } },
  ),
  technique(
    "warlock",
    30,
    "Demonology",
    "imp",
    "soul_link",
    "Soul Link",
    "shield",
    "buff",
    "#b09bc3",
    0,
    22,
    0,
    20,
    "Gain ten armor and 12% damage for eight seconds.",
    "Unbroken Soul Link",
    { buff: { duration: 8, stats: { armor: 10, power: 12 } } },
  ),
  technique(
    "warlock",
    40,
    "Destruction",
    "shadowbolt",
    "conflagrate",
    "Conflagrate",
    "fire",
    "nova",
    "#dca075",
    70,
    5,
    175,
    22,
    "A burst of fel fire burns nearby enemies.",
    "Infernal Conflagration",
  ),
  technique(
    "druid",
    20,
    "Balance",
    "wrath",
    "moonkinform",
    "Moonkin Form",
    "moon",
    "buff",
    "#a9b2db",
    0,
    24,
    0,
    20,
    "Gain 15% critical chance and eight armor for eight seconds.",
    "Astral Moonkin",
    { buff: { duration: 8, stats: { crit: 15, armor: 8 } } },
  ),
  technique(
    "druid",
    30,
    "Feral Combat",
    "thorns",
    "feralcharge",
    "Feral Charge",
    "wolf",
    "melee",
    "#c09e79",
    52,
    5,
    155,
    18,
    "A feral strike freezes nearby ordinary enemies for one second.",
    "Wildheart Charge",
    { freeze: 1 },
  ),
  technique(
    "druid",
    40,
    "Restoration",
    "moonfire",
    "swiftmend",
    "Swiftmend",
    "leaf",
    "heal",
    "#a1c88b",
    48,
    12,
    0,
    24,
    "Restore health immediately when injured.",
    "Ancient Swiftmend",
  ),
);
export const TECHNIQUE_MAP = Object.fromEntries(
  CLASS_TECHNIQUES.map((t) => [t.spell.id, t]),
) as Record<string, ClassTechnique>;
export const freshSpellbook = (core: readonly string[]): SpellbookProgress => ({
  learned: [],
  prepared: [...core],
});
export const lockedClassSpell = (
  classId: ClassId,
  id: string,
  core: readonly string[],
) =>
  id === core[0] || (["hunter", "warlock"].includes(classId) && id === core[2]);
export function normalizeSpellbook(
  classId: ClassId,
  level: number,
  raw: unknown,
  core: readonly string[],
): SpellbookProgress {
  const data =
    raw && typeof raw === "object" && !Array.isArray(raw)
      ? (raw as Record<string, unknown>)
      : {};
  const learned = Array.isArray(data.learned)
    ? [
        ...new Set(
          data.learned
            .slice(0, 32)
            .filter(
              (id): id is string =>
                typeof id === "string" &&
                Object.hasOwn(TECHNIQUE_MAP, id) &&
                TECHNIQUE_MAP[id].classId === classId &&
                level >= TECHNIQUE_MAP[id].level,
            ),
        ),
      ]
    : [];
  const known = new Set([...core, ...learned]),
    proposed = Array.isArray(data.prepared)
      ? data.prepared
          .slice(0, 32)
          .filter((id): id is string => typeof id === "string" && known.has(id))
      : [...core];
  const prepared = [...new Set(proposed)].slice(0, 4);
  if (!prepared.length) prepared.push(...core);
  for (const id of core.filter((id) => lockedClassSpell(classId, id, core))) {
    if (!prepared.includes(id)) {
      if (prepared.length === 4)
        prepared.splice(
          prepared.length -
            1 -
            [...prepared]
              .reverse()
              .findIndex((id) => !lockedClassSpell(classId, id, core)),
          1,
        );
      prepared.unshift(id);
    }
  }
  for (const id of core)
    if (prepared.length < 4 && !prepared.includes(id)) prepared.push(id);
  // The starting attack keeps its first slot. Other preparation order is retained.
  return {
    learned,
    prepared: [core[0], ...prepared.filter((id) => id !== core[0])].slice(0, 4),
  };
}
export function compatibleSpellBonus(
  spell: SpellDef,
  key: keyof SpellBonus,
): boolean {
  if (spell.kind === "buff" && !["haste", "costReduction"].includes(key))
    return false;
  if (key === "area")
    return (
      !spell.singleTarget &&
      ["melee", "nova", "orbit", "ground"].includes(spell.kind)
    );
  if (key === "projectiles" || key === "pierce")
    return (
      ["projectile", "pet", "chain"].includes(spell.kind) &&
      !(key === "pierce" && spell.kind === "chain")
    );
  if (key === "leech") return spell.kind !== "heal";
  if (key === "crit")
    return (
      (spell.kind !== "heal" && (spell.kind !== "dot" || !!spell.impact)) ||
      (spell.kind === "heal" && !spell.periodic)
    );
  if (key === "costReduction") return !!spell.cost;
  return true;
}
